    <footer class="main-footer">
       <div class="footer-content">
        <div class="footer-links">
            <a href="https://tuffdevs.atlassian.net/jira/software/projects/SCRUM/boards/1" target="_blank">Jira Project</a>
            <a href="https://github.com/106222758/tuffdevs_group_project.git" target="_blank">GitHub Repository</a>
            <a href="mailto:info@tuffdevsmedical.com">info@tuffdevsmedical.com</a>
        </div>
        <p class="copyright">&copy; 2026 TuffDev Medical. All Rights Reserved.</p>
         </div>
     </footer>
</body>
</html>