 <nav class="nav">
        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="faq.php">FAQ</a></li>
        </ul>
    </nav>

    <form action="#" method="get" class="search-bar">
        <label for="search-input" class="visually-hidden">Search our website</label>

        <button type="submit" class="search-icon-button" aria-label="search button">
            <i class="fas fa-search"></i>
        </button>

        <input type="text" id="search-input" name="q" placeholder="Search...">
    </form>
</header>